sudo: false
language: php
php:
  - "5.6"
cache:
  directories:
  - /tmp/qx5.1  
addons:
  firefox: "latest"
install:
  - cd framework
  - npm install
  - ./generate.py -sI test-source
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "php -S 0.0.0.0:31323 &> /dev/null &"
  - sleep 3
script:
  - npm run-script travis-test
after_script:
  - "pkill -f 'php -S 0.0.0.0:31323' &> /dev/null"
