sudo: false
language: php
php:
  - '5.6'
before_script:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PATH=$PWD/phantomjs-2.1.1-linux-x86_64/bin/:$PATH
script:
  - tool/test/travis/setup
  - php -S localhost:31323 1>&2 & || true
  - tool/test/travis/run http://localhost:31323/framework/test-console/index-source.html
  - pkill -f php || true
