sudo: false
language: php
env:
  - PHANTOMJS_URL=https://bitbucket.org/ariya/phantomjs/downloads PHANTOMJS_VERSION=2.1.1-linux-x86_64
php:
  - '5.6'
cache:
  directories:
  - /tmp/qx5.1  
  - $HOME/bin
before_script:
  - php -S $HOSTNAME:31324 &> /dev/null &
  - test ! -x bin/phantomjs && wget -qO - $PHANTOMJS_URL/phantomjs-${PHANTOMJS_VERSION}.tar.bz2 | tar xj --wildcards -C $HOME --strip 1 */phantomjs || true
  - export PATH=$HOME/bin/:$PATH
script:
  - tool/test/travis/setup
  - tool/test/travis/lint
  - phantomjs --debug=true tool/test/travis/run --console --url http://$HOSTNAME:31324/framework/test-travis/index-source.html
  - tool/test/travis/make-site
after_script:
  - pkill -f php &> /dev/null
